/*
 * File: app/Model/StaffModel.js
 * Date: Tue Apr 03 2012 15:23:40 GMT+0800 (ÖÐ¹ú±ê×¼Ê±¼ä)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FcSVNAdmin.model.StaffModel', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id', type: 'string'},
        {name: 'path', type: 'string'},
        {name: 'user', type: 'string'},
        {name: 'name', type: 'string'},
        {name: 'authz',type: 'string'}
    ]
});