/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_dw_comm_tws_AliWS101 */

#ifndef _Included_com_taobao_dw_comm_tws_AliWS101
#define _Included_com_taobao_dw_comm_tws_AliWS101
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_dw_comm_tws_AliWS101
 * Method:    tokenization
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_taobao_dw_comm_tws_AliWS101_tokenization
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_taobao_dw_comm_tws_AliWS101
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_taobao_dw_comm_tws_AliWS101_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_taobao_dw_comm_tws_AliWS101
 * Method:    unitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taobao_dw_comm_tws_AliWS101_unitialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
