/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alimama_loganalyzer_jobs_mrs_algo_Normalizer */

#ifndef _Included_com_alimama_loganalyzer_jobs_mrs_algo_Normalizer
#define _Included_com_alimama_loganalyzer_jobs_mrs_algo_Normalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alimama_loganalyzer_jobs_mrs_algo_Normalizer
 * Method:    normalize
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alimama_loganalyzer_jobs_mrs_algo_Normalizer_normalize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_alimama_loganalyzer_jobs_mrs_algo_Normalizer
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alimama_loganalyzer_jobs_mrs_algo_Normalizer_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_alimama_loganalyzer_jobs_mrs_algo_Normalizer
 * Method:    unitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alimama_loganalyzer_jobs_mrs_algo_Normalizer_unitialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
