/*
 * File: app/store/StaffStore.js
 * Date: Tue Apr 03 2012 15:23:40 GMT+0800 (ÖÐ¹ú±ê×¼Ê±¼ä)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FcSVNAdmin.store.StaffStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {autoLoad: true};
        me.callParent([Ext.apply({
            storeId: 'StaffStore',
            model: 'Staff',
            proxy: {
                type: 'ajax',
                url: 'action/Staff.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});