/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.ooobgy.ifnote.struts.form.CashListForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2011
 * 
 * XDoclet definition:
 * @struts.action path="/cashList" name="cashListForm" input="/user/cashList.jsp" scope="request" validate="true"
 */
public class CashListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CashListForm cashListForm = (CashListForm) form;
		
		HttpSession session = request.getSession();
		
		session.setAttribute("list_startTime", cashListForm.getStartTime());
		session.setAttribute("list_endTime", cashListForm.getEndTime());
		
		System.err.println("get:" + cashListForm.getStartTime());
		
		
		return mapping.findForward("cashList");
	}
}