/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.UserDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.UserDaoImpl;
import com.ooobgy.ifnote.entity.User;
import com.ooobgy.ifnote.struts.form.ModifyUserPswForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.action path="/modifyUserPsw" name="modifyUserPswForm" input="/modify/modifyUserPsw.jsp" scope="request" validate="true"
 */
public class ModifyUserPswAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyUserPswForm modifyUserPswForm = (ModifyUserPswForm) form;
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		user.setPassword(modifyUserPswForm.getPsw());
		UserDao dao = new UserDaoImpl();
		dao.update(user);
		
		return mapping.findForward("modifyOk");
	}
}