/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import java.sql.Timestamp;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_StockDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_StockDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Stock;
import com.ooobgy.ifnote.entity.User;
import com.ooobgy.ifnote.struts.form.NoteStockForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2011
 * 
 * XDoclet definition:
 * @struts.action path="/noteStock" name="noteStockForm" input="/inote/noteStock.jsp" scope="request" validate="true"
 */
public class NoteStockAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NoteStockForm noteStockForm = (NoteStockForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		Inote_Stock inote = (Inote_Stock) session.getAttribute("inote_stock");
		//修改
		if (inote == null) {//新增
			inote = new Inote_Stock();
		}
		
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		Calendar cal = Calendar.getInstance();
		Timestamp note_time = new Timestamp(cal.getTimeInMillis());
		inote.setUser_id(user.getId());
		inote.setNote_time(note_time);
		inote.setComment(noteStockForm.getComment());
		inote.setCount(Integer.parseInt(noteStockForm.getCount()));
		inote.setSmv(Double.parseDouble(noteStockForm.getSmv()));
		inote.setStock_code(Integer.parseInt(noteStockForm.getStock_code()));
		
		Inote_StockDao dao = new Inote_StockDaoImpl();
		if (inote.getId() == null) {
			dao.save(inote);
		} else {
			dao.update(inote);
		}
		
		session.removeAttribute("inote_stock");
		return mapping.findForward("stockList");
	}
}