/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.ooobgy.ifnote.struts.form.NoteFuturesForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2011
 * 
 * XDoclet definition:
 * @struts.action path="/noteFutures" name="noteFuturesForm" input="/inote/noteFutures.jsp" scope="request" validate="true"
 */
public class NoteFuturesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NoteFuturesForm noteFuturesForm = (NoteFuturesForm) form;// TODO Auto-generated method stub
		return null;
	}
}