/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import java.sql.Timestamp;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_DepositDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_DepositDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Deposit;
import com.ooobgy.ifnote.entity.User;
import com.ooobgy.ifnote.struts.form.NoteDepositForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2011
 * 
 * XDoclet definition:
 * @struts.action path="/noteDeposit" name="noteDepositForm" input="/inote/noteDeposit.jsp" scope="request" validate="true"
 */
public class NoteDepositAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NoteDepositForm noteDepositForm = (NoteDepositForm) form;
		HttpSession session = request.getSession();
		Inote_Deposit inoteDeposit = (Inote_Deposit) session.getAttribute("inote_deposit");
		//修改逻辑
		if (inoteDeposit == null) {//新增逻辑
			inoteDeposit = new Inote_Deposit();
		}
		
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		inoteDeposit.setUser_id(user.getId());
		Calendar cal = Calendar.getInstance();
		inoteDeposit.setNote_time(new Timestamp(cal.getTimeInMillis()));
		Integer link_id = (Integer) session.getAttribute("link_id");
		inoteDeposit.setLink_id(link_id);
		inoteDeposit.setBank_name(noteDepositForm.getBank_name());
		inoteDeposit.setComment(noteDepositForm.getComment());
		inoteDeposit.setDep_time(noteDepositForm.getDep_time());
		inoteDeposit.setRate(Double.parseDouble(noteDepositForm.getRate()));
		inoteDeposit.setSum(Double.parseDouble(noteDepositForm.getSum()));
		inoteDeposit.setType(noteDepositForm.getType());
		
		Inote_DepositDao dao = new Inote_DepositDaoImpl();
		if (inoteDeposit.getId() == null) {
			dao.save(inoteDeposit);
		} else {
			dao.update(inoteDeposit);
		}
		
		return mapping.findForward("success");
	}
}