/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.action;

import java.sql.Timestamp;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_LoanDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_LoanDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Loan;
import com.ooobgy.ifnote.entity.User;
import com.ooobgy.ifnote.struts.form.NoteLoanForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2011
 * 
 * XDoclet definition:
 * @struts.action path="/noteLoan" name="noteLoanForm" input="/inote/noteLoan.jsp" scope="request" validate="true"
 */
public class NoteLoanAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NoteLoanForm noteLoanForm = (NoteLoanForm) form;
		HttpSession session = request.getSession();
		Inote_Loan inote = (Inote_Loan) session.getAttribute("inote_loan");
		//修改
		if (inote == null) {//新增
			inote = new Inote_Loan();
		}
		
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		Calendar cal = Calendar.getInstance();
		Timestamp note_time = new Timestamp(cal.getTimeInMillis());
		inote.setUser_id(user.getId());
		inote.setNote_time(note_time);
		inote.setComment(noteLoanForm.getComment());
		inote.setBank_name(noteLoanForm.getBank_name());
		inote.setDep_time(noteLoanForm.getDep_time());
		inote.setLink_id(-1);
		inote.setType(noteLoanForm.getType());
		inote.setRate(Double.parseDouble(noteLoanForm.getRate()));
		inote.setSum(Double.parseDouble(noteLoanForm.getSum()));
		
		Inote_LoanDao dao = new Inote_LoanDaoImpl();
		if (inote.getId() == null) {
			dao.save(inote);
		} else {
			dao.update(inote);
		}
		
		return mapping.findForward("success");
	}
}