/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="delNoteForm"
 */
public class DelNoteForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -8546008575931602036L;

	/** delNid property */
	private String delNid;

	/** delType property */
	private String delType;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.delType = request.getParameter("type");
		this.delNid = request.getParameter("nid");
		System.out.println("###" + delType + "#" + delNid);
	}

	/** 
	 * Returns the delNid.
	 * @return String
	 */
	public String getDelNid() {
		return delNid;
	}

	/** 
	 * Set the delNid.
	 * @param delNid The delNid to set
	 */
	public void setDelNid(String delNid) {
		this.delNid = delNid;
	}

	/** 
	 * Returns the delType.
	 * @return String
	 */
	public String getDelType() {
		return delType;
	}

	/** 
	 * Set the delType.
	 * @param delType The delType to set
	 */
	public void setDelType(String delType) {
		this.delType = delType;
	}
}