/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import java.sql.Timestamp;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_DepositDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_DepositDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Deposit;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="depositListForm"
 */
public class DepositListForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 6509548199040818432L;

	/** startTime property */
	private String startTime;

	/** endTime property */
	private String endTime;
	
	private List<Inote_Deposit> inote_Deposits;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		ActionMessage actionMessage = new ActionMessage("list");
		errors.add("list", actionMessage);
		
		reset(mapping, request);
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		Inote_DepositDao dao = new Inote_DepositDaoImpl();
		if (startTime != null && endTime != null
				&& startTime.length() > 1 && endTime.length() > 1) {
			inote_Deposits = dao.findAllWithUidTime(user.getId(), Timestamp
					.valueOf(startTime), Timestamp.valueOf(endTime));
		} else {
			inote_Deposits = dao.findAllWithUid(user.getId());
			startTime = "";
			endTime = "";
		}
		
		super.reset(mapping, request);
	}

	/** 
	 * Returns the startTime.
	 * @return String
	 */
	public String getStartTime() {
		return startTime;
	}

	/** 
	 * Set the startTime.
	 * @param startTime The startTime to set
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return the inote_Deposits
	 */
	public List<Inote_Deposit> getInote_Deposits() {
		return inote_Deposits;
	}

	/**
	 * @param inoteDeposits the inote_Deposits to set
	 */
	public void setInote_Deposits(List<Inote_Deposit> inoteDeposits) {
		inote_Deposits = inoteDeposits;
	}
}