/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.form name="modifyUserPswForm"
 */
public class ModifyUserPswForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 694673185173157768L;

	/** oldPsw property */
	private String oldPsw;

	/** psw property */
	private String psw;

	/** psw2 property */
	private String psw2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		if (oldPsw == null || (!oldPsw.equals(user.getPassword()))) {
			ActionMessage actionMessage = new ActionMessage("error.psw");
			errors.add("oldPsw", actionMessage);
		}
		if (psw == null || psw.length() < 5) {
			ActionMessage actionMessage = new ActionMessage("reg.psw");
			errors.add("psw", actionMessage);
			if (psw2 == null || !psw2.equals(psw)) {
				ActionMessage actionMessage2 = new ActionMessage("reg.psw2");
				errors.add("psw2", actionMessage2);
			}
		}
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.oldPsw = "";
		this.psw = "";
		this.psw2 = "";
		
		super.reset(mapping, request);
	}

	/** 
	 * Returns the oldPsw.
	 * @return String
	 */
	public String getOldPsw() {
		return oldPsw;
	}

	/** 
	 * Set the oldPsw.
	 * @param oldPsw The oldPsw to set
	 */
	public void setOldPsw(String oldPsw) {
		this.oldPsw = oldPsw;
	}

	/** 
	 * Returns the psw.
	 * @return String
	 */
	public String getPsw() {
		return psw;
	}

	/** 
	 * Set the psw.
	 * @param psw The psw to set
	 */
	public void setPsw(String psw) {
		this.psw = psw;
	}

	/** 
	 * Returns the psw2.
	 * @return String
	 */
	public String getPsw2() {
		return psw2;
	}

	/** 
	 * Set the psw2.
	 * @param psw2 The psw2 to set
	 */
	public void setPsw2(String psw2) {
		this.psw2 = psw2;
	}
}