/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.form name="modifyUseInfoForm"
 */
public class ModifyUseInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 3480662170977871269L;

	/** phone property */
	private String phone;

	/** email property */
	private String email;

	/** psw property */
	private String psw;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		
		if (psw == null || (!psw.equals(user.getPassword()))) {
			ActionMessage actionMessage = new ActionMessage("error.psw");
			errors.add("psw", actionMessage);
		}
		
		if (phone == null || phone.length() != 11 || !checkphone(phone)) {
			ActionMessage actionMessage = new ActionMessage("reg.phone");
			errors.add("phone", actionMessage);
		}
		if (email == null || email.length() < 1 || !checkEmail(email)) {
			ActionMessage actionMessage = new ActionMessage("reg.email");
			errors.add("email", actionMessage);
		}
		
		return errors;
	}

	private boolean checkphone(String phone2) {
		String regex = "^(13[4,5,6,7,8,9]|15[0,8,9,1,7]|188|187)\\d{8}$";
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(phone2);
		return m.find();
	}

	private boolean checkEmail(String mail) {
		String regex = "\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(mail);
		return m.find();
	}
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.phone = "";
		this.email = "";
		this.psw = "";
		super.reset(mapping, request);
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the psw.
	 * @return String
	 */
	public String getPsw() {
		return psw;
	}

	/** 
	 * Set the psw.
	 * @param psw The psw to set
	 */
	public void setPsw(String psw) {
		this.psw = psw;
	}
}