/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_StockDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_StockDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Stock;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2011
 * 
 * XDoclet definition:
 * @struts.form name="noteStockForm"
 */
public class NoteStockForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -9142414342281714164L;

	/** count property */
	private String count;

	/** smv property */
	private String smv;

	/** stock_code property */
	private String stock_code;

	/** comment property */
	private String comment;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		
		try {
			if(Integer.parseInt(count) < 0){
				throw new IllegalArgumentException();
			}
		} catch (Throwable e) {
			ActionMessage actionMessage = new ActionMessage("error.count");
			errors.add("count", actionMessage);
			return errors;
		}
		
		try {
			if(Double.parseDouble(smv) < 0){
				throw new IllegalArgumentException();
			}
		} catch (Throwable e) {
			ActionMessage actionMessage = new ActionMessage("error.npv");
			errors.add("smv", actionMessage);
			return errors;
		}
		
		try {
			if(Integer.parseInt(stock_code) < 0){
				throw new IllegalArgumentException();
			}
		} catch (Throwable e) {
			ActionMessage actionMessage = new ActionMessage("error.code");
			errors.add("stock_code", actionMessage);
			return errors;
		}
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		String idStr = (String) request.getParameter("nid");
		if (idStr != null && idStr.length() > 0) {
			try {
				Integer id = Integer.parseInt(idStr);
				Inote_Stock inote = initInote(id);
				HttpSession session = request.getSession();
				User user = (User)session.getAttribute(SecretKey.USER_KEY);
				if (user != null && inote != null) {
					if (user.getId() == inote.getUser_id()) {
						this.comment = inote.getComment();
						this.count = inote.getCount().toString();
						this.smv = inote.getSmv().toString();
						this.stock_code = inote.getStock_code().toString();
						session.setAttribute("inote_stock", inote);
						return;
					} else {
						initBlankInote();
					}
				}
				initBlankInote();
				
				return;
			} catch (Throwable e) {
				//Do nothing,转入初始化空白Bean的操作
			}
		}
		
		initBlankInote();
	}

	/**
	 * @param id
	 * @return
	 */
	private Inote_Stock initInote(Integer id) {
		Inote_StockDao dao = new Inote_StockDaoImpl();
		Inote_Stock inote = dao.findWithId(id);
		if (inote==null || inote.getId() == null) {
			return null;
		} else {
			return inote;
		}
	}

	/**
	 * 
	 */
	private void initBlankInote() {
		this.comment = "";
		this.count = "0";
		this.smv = "1.0";
		this.stock_code = "";
	}

	/** 
	 * Returns the count.
	 * @return String
	 */
	public String getCount() {
		return count;
	}

	/** 
	 * Set the count.
	 * @param count The count to set
	 */
	public void setCount(String count) {
		this.count = count;
	}

	/** 
	 * Returns the smv.
	 * @return String
	 */
	public String getSmv() {
		return smv;
	}

	/** 
	 * Set the smv.
	 * @param smv The smv to set
	 */
	public void setSmv(String smv) {
		this.smv = smv;
	}

	/** 
	 * Returns the stock_code.
	 * @return String
	 */
	public String getStock_code() {
		return stock_code;
	}

	/** 
	 * Set the stock_code.
	 * @param stock_code The stock_code to set
	 */
	public void setStock_code(String stock_code) {
		this.stock_code = stock_code;
	}

	/** 
	 * Returns the comment.
	 * @return String
	 */
	public String getComment() {
		return comment;
	}

	/** 
	 * Set the comment.
	 * @param comment The comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}