/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_CashDao;
import com.ooobgy.ifnote.dbctrler.dao.Inote_DepositDao;
import com.ooobgy.ifnote.dbctrler.dao.Inote_FundDao;
import com.ooobgy.ifnote.dbctrler.dao.Inote_FuturesDao;
import com.ooobgy.ifnote.dbctrler.dao.Inote_LoanDao;
import com.ooobgy.ifnote.dbctrler.dao.Inote_StockDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_CashDaoImpl;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_DepositDaoImpl;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_FundDaoImpl;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_FuturesDaoImpl;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_LoanDaoImpl;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_StockDaoImpl;
import com.ooobgy.ifnote.dispbeans.Disp_Cash;
import com.ooobgy.ifnote.dispbeans.Disp_Deposit;
import com.ooobgy.ifnote.dispbeans.Disp_Fund;
import com.ooobgy.ifnote.dispbeans.Disp_Futures;
import com.ooobgy.ifnote.dispbeans.Disp_Loan;
import com.ooobgy.ifnote.dispbeans.Disp_Stock;
import com.ooobgy.ifnote.entity.Inote_Cash;
import com.ooobgy.ifnote.entity.Inote_Deposit;
import com.ooobgy.ifnote.entity.Inote_Fund;
import com.ooobgy.ifnote.entity.Inote_Futures;
import com.ooobgy.ifnote.entity.Inote_Loan;
import com.ooobgy.ifnote.entity.Inote_Stock;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="summaryForm"
 */
public class SummaryForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6326747524547499827L;

	private List<Disp_Cash> disp_Cashs;
	private Double sum_cash;
	private List<Disp_Deposit> disp_Deposits;
	private Double sum_deposit;
	private Double earn_deposit;
	private List<Disp_Fund> disp_Funds;
	private Double sum_fund;
	private Double earn_fund;
	private List<Disp_Futures> disp_Futures;
	private Double sum_futures;
	private Double earn_futures;
	private List<Disp_Loan> disp_Loans;
	private Double sum_loan;
	private Double earn_loan;
	private List<Disp_Stock> disp_Stocks;
	private Double sum_stock;
	private Double earn_stock;
	
	private Double sum_total;
	private Double earn_total;

	private Integer userId;
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		ActionMessage actionMessage = new ActionMessage("list");
		errors.add("list", actionMessage);
		
		reset(mapping, request);
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		this.userId = user.getId();
		
		init();
		summary();
	}

	/**
	 * 
	 */
	private void summary() {
		this.sum_total = this.sum_cash + this.sum_deposit
							+ this.sum_fund + this.sum_futures
							+ this.sum_loan + this.sum_stock;
		this.earn_total = this.earn_deposit + this.earn_fund
							+ this.earn_futures + this.earn_loan
							+ this.earn_stock;
	}

	/**
	 * 
	 */
	private void init() {
		initCash();
		initDeposit();
		initFund();
		initFutures();
		initLoan();
		initStock();
	}

	/**
	 * 
	 */
	private void initStock() {
		this.earn_stock = 0.0;
		this.sum_stock = 0.0;
		
		Inote_StockDao dao = new Inote_StockDaoImpl();
		List<Inote_Stock> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Stock inote : inotes) {
			Disp_Stock dispStock = new Disp_Stock(inote);
			dispStock.init();
			if (i < 5) {//打印最新5条
				this.disp_Stocks.add(dispStock);
			}
			this.earn_stock += dispStock.getProfit();
			this.sum_stock += dispStock.getAsset();
			
			i++;
		}
	}

	/**
	 * 
	 */
	private void initLoan() {
		this.earn_loan = 0.0;
		this.sum_loan = 0.0;
		
		Inote_LoanDao dao = new Inote_LoanDaoImpl();
		List<Inote_Loan> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Loan inote : inotes) {
			Disp_Loan dispLoan = new Disp_Loan(inote);
			dispLoan.init();
			if (i < 5) {
				this.disp_Loans.add(dispLoan);
			}
			this.earn_loan += dispLoan.getProfit();
			this.sum_loan += dispLoan.getAsset();
			
			i++;
		}
		
	}

	/**
	 * 
	 */
	private void initFutures() {
		this.earn_futures = 0.0;
		this.sum_futures = 0.0;
		
		Inote_FuturesDao dao = new Inote_FuturesDaoImpl();
		List<Inote_Futures> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Futures inote : inotes) {
			Disp_Futures dispFutures = new Disp_Futures(inote);
			dispFutures.init();
			if (i < 5) {
				this.disp_Futures.add(dispFutures);
			}
			this.earn_futures += dispFutures.getProfit();
			this.sum_futures += dispFutures.getProfit();
			
			i++;
		}
	}

	/**
	 * 
	 */
	private void initFund() {
		this.earn_fund = 0.0;
		this.sum_fund = 0.0;
		
		Inote_FundDao dao = new Inote_FundDaoImpl();
		List<Inote_Fund> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Fund inote : inotes) {
			Disp_Fund dispFund = new Disp_Fund(inote);
			dispFund.init();
			if (i < 5) {
				this.disp_Funds.add(dispFund);
			}
			this.earn_fund += dispFund.getProfit();
			this.sum_fund += dispFund.getAsset();
			
			i++;
		}
		
	}

	/**
	 * 
	 */
	private void initDeposit() {
		this.earn_deposit = 0.0;
		this.sum_deposit = 0.0;
		
		Inote_DepositDao dao = new Inote_DepositDaoImpl();
		List<Inote_Deposit> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Deposit inote : inotes) {
			Disp_Deposit dispDeposit = new Disp_Deposit(inote);
			dispDeposit.init();
			if (i < 5) {
				this.disp_Deposits.add(dispDeposit);
			}
			this.earn_deposit += dispDeposit.getProfit();
			this.sum_deposit += dispDeposit.getAsset();
			
			i++;
		}
		
	}

	/**
	 * 
	 */
	private void initCash() {
		this.sum_cash = 0.0;
		
		Inote_CashDao dao = new Inote_CashDaoImpl();
		List<Inote_Cash> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Cash inote : inotes) {
			Disp_Cash dispCash = new Disp_Cash(inote);
			dispCash.init();
			if (i < 5) {
				this.disp_Cashs.add(dispCash);
			}
			this.sum_cash += dispCash.getAccount();
			
			i++;
		}
		
	}

	/**
	 * @return the disp_Cashs
	 */
	public List<Disp_Cash> getDisp_Cashs() {
		return disp_Cashs;
	}

	/**
	 * @param dispCashs the disp_Cashs to set
	 */
	public void setDisp_Cashs(List<Disp_Cash> dispCashs) {
		disp_Cashs = dispCashs;
	}

	/**
	 * @return the sum_cash
	 */
	public Double getSum_cash() {
		return sum_cash;
	}

	/**
	 * @param sumCash the sum_cash to set
	 */
	public void setSum_cash(Double sumCash) {
		sum_cash = sumCash;
	}

	/**
	 * @return the disp_Deposits
	 */
	public List<Disp_Deposit> getDisp_Deposits() {
		return disp_Deposits;
	}

	/**
	 * @param dispDeposits the disp_Deposits to set
	 */
	public void setDisp_Deposits(List<Disp_Deposit> dispDeposits) {
		disp_Deposits = dispDeposits;
	}

	/**
	 * @return the sum_deposit
	 */
	public Double getSum_deposit() {
		return sum_deposit;
	}

	/**
	 * @param sumDeposit the sum_deposit to set
	 */
	public void setSum_deposit(Double sumDeposit) {
		sum_deposit = sumDeposit;
	}

	/**
	 * @return the earn_deposit
	 */
	public Double getEarn_deposit() {
		return earn_deposit;
	}

	/**
	 * @param earnDeposit the earn_deposit to set
	 */
	public void setEarn_deposit(Double earnDeposit) {
		earn_deposit = earnDeposit;
	}

	/**
	 * @return the disp_Funds
	 */
	public List<Disp_Fund> getDisp_Funds() {
		return disp_Funds;
	}

	/**
	 * @param dispFunds the disp_Funds to set
	 */
	public void setDisp_Funds(List<Disp_Fund> dispFunds) {
		disp_Funds = dispFunds;
	}

	/**
	 * @return the sum_fund
	 */
	public Double getSum_fund() {
		return sum_fund;
	}

	/**
	 * @param sumFund the sum_fund to set
	 */
	public void setSum_fund(Double sumFund) {
		sum_fund = sumFund;
	}

	/**
	 * @return the earn_fund
	 */
	public Double getEarn_fund() {
		return earn_fund;
	}

	/**
	 * @param earnFund the earn_fund to set
	 */
	public void setEarn_fund(Double earnFund) {
		earn_fund = earnFund;
	}

	/**
	 * @return the disp_Futures
	 */
	public List<Disp_Futures> getDisp_Futures() {
		return disp_Futures;
	}

	/**
	 * @param dispFutures the disp_Futures to set
	 */
	public void setDisp_Futures(List<Disp_Futures> dispFutures) {
		disp_Futures = dispFutures;
	}

	/**
	 * @return the sum_futures
	 */
	public Double getSum_futures() {
		return sum_futures;
	}

	/**
	 * @param sumFutures the sum_futures to set
	 */
	public void setSum_futures(Double sumFutures) {
		sum_futures = sumFutures;
	}

	/**
	 * @return the earn_futures
	 */
	public Double getEarn_futures() {
		return earn_futures;
	}

	/**
	 * @param earnFutures the earn_futures to set
	 */
	public void setEarn_futures(Double earnFutures) {
		earn_futures = earnFutures;
	}

	/**
	 * @return the disp_Loans
	 */
	public List<Disp_Loan> getDisp_Loans() {
		return disp_Loans;
	}

	/**
	 * @param dispLoans the disp_Loans to set
	 */
	public void setDisp_Loans(List<Disp_Loan> dispLoans) {
		disp_Loans = dispLoans;
	}

	/**
	 * @return the sum_loan
	 */
	public Double getSum_loan() {
		return sum_loan;
	}

	/**
	 * @param sumLoan the sum_loan to set
	 */
	public void setSum_loan(Double sumLoan) {
		sum_loan = sumLoan;
	}

	/**
	 * @return the earn_loan
	 */
	public Double getEarn_loan() {
		return earn_loan;
	}

	/**
	 * @param earnLoan the earn_loan to set
	 */
	public void setEarn_loan(Double earnLoan) {
		earn_loan = earnLoan;
	}

	/**
	 * @return the disp_Stocks
	 */
	public List<Disp_Stock> getDisp_Stocks() {
		return disp_Stocks;
	}

	/**
	 * @param dispStocks the disp_Stocks to set
	 */
	public void setDisp_Stocks(List<Disp_Stock> dispStocks) {
		disp_Stocks = dispStocks;
	}

	/**
	 * @return the sum_stock
	 */
	public Double getSum_stock() {
		return sum_stock;
	}

	/**
	 * @param sumStock the sum_stock to set
	 */
	public void setSum_stock(Double sumStock) {
		sum_stock = sumStock;
	}

	/**
	 * @return the earn_stock
	 */
	public Double getEarn_stock() {
		return earn_stock;
	}

	/**
	 * @param earnStock the earn_stock to set
	 */
	public void setEarn_stock(Double earnStock) {
		earn_stock = earnStock;
	}

	/**
	 * @return the sum_total
	 */
	public Double getSum_total() {
		return sum_total;
	}

	/**
	 * @param sumTotal the sum_total to set
	 */
	public void setSum_total(Double sumTotal) {
		sum_total = sumTotal;
	}

	/**
	 * @return the earn_total
	 */
	public Double getEarn_total() {
		return earn_total;
	}

	/**
	 * @param earnTotal the earn_total to set
	 */
	public void setEarn_total(Double earnTotal) {
		earn_total = earnTotal;
	}

	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}