/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ooobgy.ifnote.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ooobgy.ifnote.constants.SecretKey;
import com.ooobgy.ifnote.dbctrler.dao.Inote_StockDao;
import com.ooobgy.ifnote.dbctrler.daoimpl.Inote_StockDaoImpl;
import com.ooobgy.ifnote.entity.Inote_Cash;
import com.ooobgy.ifnote.entity.Inote_Deposit;
import com.ooobgy.ifnote.entity.Inote_Fund;
import com.ooobgy.ifnote.entity.Inote_Futures;
import com.ooobgy.ifnote.entity.Inote_Loan;
import com.ooobgy.ifnote.entity.Inote_Stock;
import com.ooobgy.ifnote.entity.User;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="summaryForm"
 */
public class SummaryForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6326747524547499827L;

	private List<Inote_Cash> inote_Cashs;
	private Double sum_cash;
	private List<Inote_Deposit> inote_Deposits;
	private Double sum_deposit;
	private Double earn_deposit;
	private List<Inote_Fund> inote_Funds;
	private Double sum_fund;
	private Double earn_fund;
	private List<Inote_Futures> inote_Futures;
	private Double sum_futures;
	private Double earn_futures;
	private List<Inote_Loan> inote_Loans;
	private Double sum_loan;
	private Double earn_loan;
	private List<Inote_Stock> inote_Stocks;
	private Double sum_stock;
	private Double earn_stock;
	
	private Double sum_total;
	private Double earn_total;

	private Integer userId;
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		ActionMessage actionMessage = new ActionMessage("list");
		errors.add("list", actionMessage);
		
		reset(mapping, request);
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute(SecretKey.USER_KEY);
		this.userId = user.getId();
		
		init();
		summary();
	}

	/**
	 * 
	 */
	private void summary() {
		this.sum_total = this.sum_cash + this.sum_deposit
							+ this.sum_fund + this.sum_futures
							+ this.sum_loan + this.sum_stock;
		this.earn_total = this.earn_deposit + this.earn_fund
							+ this.earn_futures + this.earn_loan
							+ this.earn_stock;
	}

	/**
	 * 
	 */
	private void init() {
		initCash();
		initDeposit();
		initFund();
		initFutures();
		initLoan();
		initStock();
	}

	/**
	 * 
	 */
	private void initStock() {
		this.earn_stock = 0.0;
		this.sum_stock = 0.0;
		
		Inote_StockDao dao = new Inote_StockDaoImpl();
		List<Inote_Stock> inotes = dao.findAllWithUid(userId);
		int i = 0;
		for (Inote_Stock inote : inotes) {
			if (i < 5) {//打印最新5条
				this.inote_Stocks.add(inote);
			}
			
			
			i++;
		}
	}

	/**
	 * 
	 */
	private void initLoan() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * 
	 */
	private void initFutures() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * 
	 */
	private void initFund() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * 
	 */
	private void initDeposit() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * 
	 */
	private void initCash() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * @return the inote_Cashs
	 */
	public List<Inote_Cash> getInote_Cashs() {
		return inote_Cashs;
	}

	/**
	 * @param inoteCashs the inote_Cashs to set
	 */
	public void setInote_Cashs(List<Inote_Cash> inoteCashs) {
		inote_Cashs = inoteCashs;
	}

	/**
	 * @return the inote_Deposits
	 */
	public List<Inote_Deposit> getInote_Deposits() {
		return inote_Deposits;
	}

	/**
	 * @param inoteDeposits the inote_Deposits to set
	 */
	public void setInote_Deposits(List<Inote_Deposit> inoteDeposits) {
		inote_Deposits = inoteDeposits;
	}

	/**
	 * @return the inote_Funds
	 */
	public List<Inote_Fund> getInote_Funds() {
		return inote_Funds;
	}

	/**
	 * @param inoteFunds the inote_Funds to set
	 */
	public void setInote_Funds(List<Inote_Fund> inoteFunds) {
		inote_Funds = inoteFunds;
	}

	/**
	 * @return the inote_Futures
	 */
	public List<Inote_Futures> getInote_Futures() {
		return inote_Futures;
	}

	/**
	 * @param inoteFutures the inote_Futures to set
	 */
	public void setInote_Futures(List<Inote_Futures> inoteFutures) {
		inote_Futures = inoteFutures;
	}

	/**
	 * @return the inote_Loans
	 */
	public List<Inote_Loan> getInote_Loans() {
		return inote_Loans;
	}

	/**
	 * @param inoteLoans the inote_Loans to set
	 */
	public void setInote_Loans(List<Inote_Loan> inoteLoans) {
		inote_Loans = inoteLoans;
	}

	/**
	 * @return the inote_Stocks
	 */
	public List<Inote_Stock> getInote_Stocks() {
		return inote_Stocks;
	}

	/**
	 * @param inoteStocks the inote_Stocks to set
	 */
	public void setInote_Stocks(List<Inote_Stock> inoteStocks) {
		inote_Stocks = inoteStocks;
	}

	/**
	 * @return the sum_cash
	 */
	public Double getSum_cash() {
		return sum_cash;
	}

	/**
	 * @param sumCash the sum_cash to set
	 */
	public void setSum_cash(Double sumCash) {
		sum_cash = sumCash;
	}

	/**
	 * @return the sum_deposit
	 */
	public Double getSum_deposit() {
		return sum_deposit;
	}

	/**
	 * @param sumDeposit the sum_deposit to set
	 */
	public void setSum_deposit(Double sumDeposit) {
		sum_deposit = sumDeposit;
	}

	/**
	 * @return the earn_deposit
	 */
	public Double getEarn_deposit() {
		return earn_deposit;
	}

	/**
	 * @param earnDeposit the earn_deposit to set
	 */
	public void setEarn_deposit(Double earnDeposit) {
		earn_deposit = earnDeposit;
	}

	/**
	 * @return the sum_fund
	 */
	public Double getSum_fund() {
		return sum_fund;
	}

	/**
	 * @param sumFund the sum_fund to set
	 */
	public void setSum_fund(Double sumFund) {
		sum_fund = sumFund;
	}

	/**
	 * @return the earn_fund
	 */
	public Double getEarn_fund() {
		return earn_fund;
	}

	/**
	 * @param earnFund the earn_fund to set
	 */
	public void setEarn_fund(Double earnFund) {
		earn_fund = earnFund;
	}

	/**
	 * @return the sum_futures
	 */
	public Double getSum_futures() {
		return sum_futures;
	}

	/**
	 * @param sumFutures the sum_futures to set
	 */
	public void setSum_futures(Double sumFutures) {
		sum_futures = sumFutures;
	}

	/**
	 * @return the earn_futures
	 */
	public Double getEarn_futures() {
		return earn_futures;
	}

	/**
	 * @param earnFutures the earn_futures to set
	 */
	public void setEarn_futures(Double earnFutures) {
		earn_futures = earnFutures;
	}

	/**
	 * @return the sum_loan
	 */
	public Double getSum_loan() {
		return sum_loan;
	}

	/**
	 * @param sumLoan the sum_loan to set
	 */
	public void setSum_loan(Double sumLoan) {
		sum_loan = sumLoan;
	}

	/**
	 * @return the earn_loan
	 */
	public Double getEarn_loan() {
		return earn_loan;
	}

	/**
	 * @param earnLoan the earn_loan to set
	 */
	public void setEarn_loan(Double earnLoan) {
		earn_loan = earnLoan;
	}

	/**
	 * @return the sum_stock
	 */
	public Double getSum_stock() {
		return sum_stock;
	}

	/**
	 * @param sumStock the sum_stock to set
	 */
	public void setSum_stock(Double sumStock) {
		sum_stock = sumStock;
	}

	/**
	 * @return the earn_stock
	 */
	public Double getEarn_stock() {
		return earn_stock;
	}

	/**
	 * @param earnStock the earn_stock to set
	 */
	public void setEarn_stock(Double earnStock) {
		earn_stock = earnStock;
	}

	/**
	 * @return the sum_total
	 */
	public Double getSum_total() {
		return sum_total;
	}

	/**
	 * @param sumTotal the sum_total to set
	 */
	public void setSum_total(Double sumTotal) {
		sum_total = sumTotal;
	}

	/**
	 * @return the earn_total
	 */
	public Double getEarn_total() {
		return earn_total;
	}

	/**
	 * @param earnTotal the earn_total to set
	 */
	public void setEarn_total(Double earnTotal) {
		earn_total = earnTotal;
	}

	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}