/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_dw_comm_tws_TwsTokenization */

#ifndef _Included_com_taobao_dw_comm_tws_TwsTokenization
#define _Included_com_taobao_dw_comm_tws_TwsTokenization
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_dw_comm_tws_TwsTokenization
 * Method:    tokenization
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_taobao_dw_comm_tws_TwsTokenization_tokenization
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_taobao_dw_comm_tws_TwsTokenization
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_taobao_dw_comm_tws_TwsTokenization_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_taobao_dw_comm_tws_TwsTokenization
 * Method:    unitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taobao_dw_comm_tws_TwsTokenization_unitialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
